### ISSUE TITLE
Store & use meta-schemas

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/jsonschema-rs#28]
If we'll validate the input schemas for conformance to the respective specs, then:

- We probably can skip a lot of our own checks during the compilation process
- There will be an understandable error message in case if the input schema is not valid

Regarding the implementation details - it can be done via `lazy_static!` so the schema is not re-compiled. In the perfect scenario I'd like to have it done via code-generation (like described here - #46)

**Comment by darwin67** [comment]
It would be helpful to have better schema validation error messages.
We don't need code generation since the schemas are not pre-defined and are stored in a database. But without better error messages for schemas themselves, it's pretty hard for someone who might not be familiar with the specs to figure what they did wrong.

**Comment by Stranger6667** [comment]
Sorry @darwin67 I missed your message.
The error messages should be covered by #100 - I hope to work on it in the next few months
