### ISSUE TITLE
Is it expected that email validation is a bit incomplete?

### ISSUE THREAD

**Issue by qrilka** [Stranger6667/jsonschema-rs#471]
In https://github.com/Stranger6667/jsonschema-rs/blob/79e35a2012e49ee7af58c6f8b9b10ff2ff0b0dff/jsonschema/src/keywords/format.rs#L122-L140 I see that email validation doesn't check for non-printable characters and explicitly says that domain validation is not done

**Comment by Stranger6667** [comment]
That is deliberately simplistic, but I am open to extending it. [From the spec](https://json-schema.org/draft/2020-12/json-schema-validation#name-implementation-requirements):

> When the implementation is configured for assertion behavior, it:
> SHOULD provide an implementation-specific best effort validation for each format attribute defined below;
> MAY choose to implement validation of any or all format attributes as a no-op by always producing a validation result of true;

**Comment by jqnatividad** [comment]
Perhaps, as a feature, have extended email validation using https://github.com/johnstonskj/rust-email_address?

Also, with the custom keyword/format support, is there an ability to override the built-in keywords/formats should the user want a more robust implementation?

**Comment by Stranger6667** [comment]
> Perhaps, as a feature, have extended email validation using https://github.com/johnstonskj/rust-email_address?

Great idea! I am inclined to have some "full" feature (enabled by default) that will include extra dependencies, mainly for format validation. This is basically the idea from #470 and there are no blockers to implement it and include a more robust email validation. I'd be happy to review a PR for this, otherwise, I'll take a look at it in a few weeks.

> Also, with the custom keyword/format support, is there an ability to override the built-in keywords/formats should the user want a more robust implementation?

Yep, overridden keywords & formats have the preference
